name: AI Pull Request Review

on:
  issue_comment:
    types: [created]

jobs:
  ai-review:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request != '' &&
      startsWith(github.event.comment.body, '/review')
    steps:
      - uses: actions/checkout@v4

      - name: Run free AI PR review
        uses: qodo-ai/pr-agent@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
