name: AI Pull Request Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run free AI PR review
        uses: qodo-ai/pr-agent@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
